/* ============================================================
   Splitbaby — Firebase project config

   Generated by the Firebase CLI from project splitbaby-b002-b603.

   This is NOT a secret. A web API key is a public project
   identifier that merely says which project a request is for;
   Firestore security rules are what actually control access.
   See firestore.rules.
   ============================================================ */

export const FIREBASE_CONFIG = {
  apiKey:            "AIzaSyA07K0adRolVqreGyfYplb0XwjVwTc02Vk",
  authDomain:        "splitbaby-b002-b603.firebaseapp.com",
  projectId:         "splitbaby-b002-b603",
  storageBucket:     "splitbaby-b002-b603.firebasestorage.app",
  messagingSenderId: "997850950307",
  appId:             "1:997850950307:web:7a658fc9eada4a426b2d16"
};
